### ISSUE TITLE
Caido Plugin

### ISSUE THREAD

**Issue by Sytten** [projectdiscovery/interactsh#1031]
Hi Project Discovery!

Caido founder here, our community created a new plugin for Caido for interactsh:
https://github.com/caido-community/quickssrf

If you can add it to the readme 🙏 

Thanks a lot ❤

**Comment by Ice3man543** [comment]
Hi @Sytten,

Added here: https://github.com/projectdiscovery/interactsh/pull/1032.

Thanks for the amazing tool!

**Comment by Sytten** [comment]
Thanks a lot @Ice3man543
