### ISSUE TITLE
Error running interactsh on pc or vps

### ISSUE THREAD

**Issue by Sy3Omda** [projectdiscovery/interactsh#129]
### Interactsh version: 0.0.6

When run # interactsh-client -v 
[FTL] Could not create client: could not make register request: POST https://interactsh.com/register giving up after 6 attempts: Post "https://interactsh.com/register": read tcp 192.168.8.106:44800->104.248.51.21:443: read: connection reset by peer

**Comment by d4op** [comment]
_       __                       __       __
   (_)___  / /____  _________ ______/ /______/ /_
  / / __ \/ __/ _ \/ ___/ __ '/ ___/ __/ ___/ __ \
 / / / / / /_/  __/ /  / /_/ / /__/ /_(__  ) / / /
/_/_/ /_/\__/\___/_/   \__,_/\___/\__/____/_/ /_/ v0.0.6

                projectdiscovery.io

[FTL] Could not create client: could not make register request: POST https://interactsh.com/register giving up after 6 attempts: Post "https://interactsh.com/register": dial tcp 104.248.51.21:443: connect: connection refused

**Comment by ehsandeep** [comment]
@d4op @Sy3Omda should be fixed with latest release https://github.com/projectdiscovery/interactsh/releases/tag/v0.0.7
