### ISSUE TITLE
Can't connect to my custom interactsh server

### ISSUE THREAD

**Issue by JoshuaMart** [projectdiscovery/interactsh#135]
Hi,
Following the instructions I set up my own Interactsh server, however after starting it, I can't connect to it with the interactsh client.

Server running : 
![interactsh](https://user-images.githubusercontent.com/17493961/146652935-9a81a7e9-5a34-4180-960c-6f679add6f7c.png)

Attempt to connect with the client : 
![interact2](https://user-images.githubusercontent.com/17493961/146652796-cc257760-e10e-4124-bff2-af01a35b7e00.png)

![curl](https://user-images.githubusercontent.com/17493961/146652820-7ff8856f-0482-4921-9451-923a0b980efe.png)

And I think my DNS configuration is good because if I run a custom DNS that I wrote in Ruby, it responds well to queries
![dns](https://user-images.githubusercontent.com/17493961/146652868-969507c5-c3c4-49f4-9712-f22baf1d7ddd.png)

Regards

**Comment by ehsandeep** [comment]
@JoshuaMart this might be related to ongoing issue related to SSL server and we are tracking it here - https://github.com/projectdiscovery/interactsh/issues/127, most probably the HTTPS server is not running in your self-hosted instance as well, using `-server http://DOMAIN.com` should work.

**Comment by JoshuaMart** [comment]
Hi,
If you look the second screenshot, I've tried with http and https :) 

Regards

**Comment by user123bvtrbrtntr** [comment]
Hi, I have the same issue. Is there any debugging tips or information I could provide to facilitate the process?
The only difference in my installation process is that I used an Azure VM instead of DigitalOcean droplet.

**Comment by EndPositive** [comment]
I'm having the same issue. ZAP's interactsh client does work, so it seems to be an issue in the client and not the server.

Their register code is here: https://github.com/zaproxy/zap-extensions/blob/9394dabee50bfbcdf92af232a44c1b93652aa52b/addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshService.java#L148

**Comment by ehsandeep** [comment]
> I'm having the same issue. ZAP's interactsh client does work, so it seems to be an issue in the client and not the server.
> 
> Their register code is here: https://github.com/zaproxy/zap-extensions/blob/9394dabee50bfbcdf92af232a44c1b93652aa52b/addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshService.java#L148

this might be related to interactsh server in use at https://github.com/zaproxy/zap-extensions/blob/3261bf26c3fb23796441f1a59d79c47f764301cb/addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshParam.java#L54, currently, **interactsh.com** is down due to known issue we are tracking here https://github.com/projectdiscovery/interactsh/issues/127 and **interact.sh** is used across all projects.

**Comment by EndPositive** [comment]
No, I'm using a privately hosted interactsh server in ZAP as well. In ZAP is does work, in Nuclei / interactsh-client it does not. I'll add a debugger to interactsh-client locally and inform you with better req/resp traces.

**Comment by EndPositive** [comment]
@ehsandeep you can reproduce the problem on the public interactsh server as well:

`interactsh-client -server https://interact.sh/`

Note the / at the end. The request will be made using `https://interact.sh//register`. The response is:

```
{"error":"could not decode json body: EOF"}
```

**Comment by EndPositive** [comment]
The issue propagates to Nuclei, so starting nuclei without the trailing / is a workaround

**Comment by JoshuaMart** [comment]
I managed to set up in a different way

@EndPositive That's actually another problem I think :)

**Comment by ehsandeep** [comment]
@JoshuaMart is it possible to share the root cause of this issue that you identified/fixed it eventually? information might be helpful as other users are facing similar issues https://github.com/projectdiscovery/interactsh/issues/146

**Comment by JoshuaMart** [comment]
As I did not succeed in following the steps described and after several tries, I can't get a configuration without subdomain, by modifying the NS of the domain, I set up a sub-domain and there I could do it

So instead of having for example :
```
ns1.domain.tld NS server_ip
```

I have
```
interact.bnty.ovh NS ns1.interact.domain.tld
ns1.interact.domain.tld A server_ip
```

![image](https://user-images.githubusercontent.com/17493961/147454180-cab0acb6-8b30-49ef-a57f-4eaf6ad63b2b.png)

And with this configuration it works
