### ISSUE TITLE
Interactsh-server -smb and -responder flags not working on EC2 hosted instance

### ISSUE THREAD

**Issue by defec8edc0de** [projectdiscovery/interactsh#140]
### Current Behavior:

I installed `interactsh-server` with all dependencies (go, docker, python3, latest impacket) on a fresh AWS EC2 t2.micro Ubuntu 20.04 server x64 AMI instance with a public elastic IP and did setup as documented a `.com` domain on GoDaddy.
Everything works as intended so far, except the `-responder` and `-smb` flags. When started as follows:

```
# interactsh-server -domain {{myserver.com}} -root-tld -debug -ip {{PublicEIP-of-myserver.com}} -listen-ip 0.0.0.0 -token {{mytoken}} -responder
2021/12/23 10:17:38 TLS certificates are not expiring, continue!
2021/12/23 10:17:38 Listening on DNS, SMTP and HTTP ports

# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      612/sshd: /usr/sbin 
tcp6       0      0 :::25                   :::*                    LISTEN      2043/interactsh-ser 
tcp6       0      0 :::443                  :::*                    LISTEN      2043/interactsh-ser 
tcp6       0      0 :::587                  :::*                    LISTEN      2043/interactsh-ser 
tcp6       0      0 :::80                   :::*                    LISTEN      2043/interactsh-ser 
tcp6       0      0 :::465                  :::*                    LISTEN      2043/interactsh-ser 
tcp6       0      0 :::22                   :::*                    LISTEN      612/sshd: /usr/sbin 
udp        0      0 172.31.13.30:68         0.0.0.0:*                           377/systemd-network 
udp6       0      0 :::53                   :::*                                2043/interactsh-se
```
It can be seen, no errors are shown in the debug Stdout logs, and no responder ports are open. The same behaviour for the `-smb` flag.
I confirmed that `smbserver.py` from Impacket is in PATH and can be executed as root.
As of [smb](https://github.com/projectdiscovery/interactsh/blob/main/pkg/server/smb_server.go#L51) I confirmed that `# python3 smb_server.py /tmp` works.
As of [responder](https://github.com/projectdiscovery/interactsh/blob/main/pkg/server/responder_server.go#L51), the image wasn't found on Docker Hub:
```
# docker run -p 137:137/udp -p  138:138/udp -p 389:389 -p 1433:1433 -p 1434:1434/udp -p 135:135 -p 139:139 -p 445:445 -p 21:21 -p 3141:3141 -p 110:110 -p 3128:3128 -p 5355:5355/udp -v /tmp:/tmp/opt/Responder/logs --rm interactsh:latest
Unable to find image 'interactsh:latest' locally
docker: Error response from daemon: pull access denied for interactsh, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
When I build this myself with ```docker build -t interactsh:latest .``` from the [Dockerfile](https://github.com/projectdiscovery/interactsh/blob/main/cmd/interactsh-server/Dockerfile) and start this Responder image as above, I get

```
# docker run -p 137:137/udp -p  138:138/udp -p 389:389 -p 1433:1433 -p 1434:1434/udp -p 135:135 -p 139:139 -p 445:445 -p 21:21 
-p 3141:3141 -p 110:110 -p 3128:3128 -p 5355:5355/udp -v /tmp:/tmp/opt/Responder/logs --rm interactsh:latest
You need to install python-netifaces or run Responder with python3...
Try "apt-get install python-netifaces" or "pip install netifaces"
```

### Expected Behavior:
- SMB listener (TCP/445) with `-smb` flag
- Responder listeners (UDP/137,138,1434,5355 and TCP/21,110,135,139,389,445,1433,3141,3128) with `-responder` flag
- Errors with exception message/stacktrace in debug stdout logs when the listeners can't be started

**Comment by Mzack9999** [comment]
@defec8edc0de, thanks for opening and detailing the issue. The impacket docker image was missing a dependency due to a recent change. This should be fixed in #143. Please let me know if you are still facing any issues.

**Comment by defec8edc0de** [comment]
Thank you, I confirm this fixed the `-responder` issue.
Still open are the subissues, that `-smb` is not working and no error (or success) messages are shown in the debug log of the interactsh-server.

**Comment by Mzack9999** [comment]
@defec8edc0de I tried a few times on new Linux boxes, but the samba server always runs correctly. Could you confirm if the following command runs successfully on the EC2 instance:
```console
$ python3 smb_server.py log.txt 445
```
And the file `log.txt` contains the following:
```console
$ cat log.txt
12/29/2021 02:39:15 PM: INFO: Config file parsed
```

**Comment by defec8edc0de** [comment]
Yes I confirm the above commands work on my EC2 instance.

**Comment by derekkddj** [comment]
Hi, i have problems with the "responder" flag, is not working. I have the docker image locally, but the "interactsh-server" is not runnign the "docker run" command, neither looking for changes in the logs in the /tmp folder.
