### ISSUE TITLE
Connection Refused connecting to private server

### ISSUE THREAD

**Issue by bluesm866** [projectdiscovery/interactsh#146]
Version: 0.0.7
Go version: 1.17.5 linux/amd64
Hello guys, the issue I'm having is trying to connect the client to my server.
I execute the command:
`interactsh-client -server https://bm866.cc `

The server returns:
```
[FTL] Could not create client: could not make register request: POST https://bm866.cc/register giving up after 6 attempts: Post "https://bm866.cc/register": dial tcp 168.138.128.154
:443: connect: connection refused
```

I also tried _http://bm866.cc_ with the same response.
And I also tried the web client with custom server pointing to bm866.cc with no success.

My server is running on an _Oracle VM_. 
My domain in registered on _Namecheap_.
I configured it with custom nameservers (ns1 and ns2 both pointing to _168.138.128.154_, which is the VM's IP).
I am running _BIND9_ on it to act as nameserver.
If I enable _nginx_ on my VM I can access it using _http://bm866.cc_.
If I run _nslookup ubuntu.com bm866.cc_ from my Windows PC I get the correct response.
I start my server with this command:
`interactsh-server -domain bm866.cc`

The response I get leads me to believe it is running correctly:
```
2021/12/26 21:06:20 Creating new order for domains: [*.bm866.cc bm866.cc]
2021/12/26 21:06:21 Order created: https://acme-v02.api.letsencrypt.org/acme/orde                                                                                       r/337280780/50384353190
2021/12/26 21:06:21 Fetching authorization: https://acme-v02.api.letsencrypt.org/                                                                                       acme/authz-v3/62268156840
2021/12/26 21:06:21 Fetched authorization: bm866.cc
2021/12/26 21:06:31 Updating challenge for authorization bm866.cc: https://acme-v02.api.letsencrypt.org/acme/chall-v3/62268156840/Wnqorg
2021/12/26 21:06:33 Listening on DNS, SMTP and HTTP ports
```
I tried shutting down my firewall to see if it was interfering in some way with the command _sudo iptables -F_. I also made sure ports 53, 80 and 443 were open for TCP packets on the VM configuration.

Even so, I am getting connection refused.

**Comment by ehsandeep** [comment]
@bluesm866 to confirm if all the services are running properly, can you share the output of `netstat -tulpn` after running interactsh server or pull the to `dev` branch with `git checkout dev` and build the interactsh server that includes some error handling and probably will display the error details.

**Comment by bluesm866** [comment]
Hello ehsandeep,
This is the netstat result:
Active Internet connections (only servers)
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 10.0.0.128:53           0.0.0.0:*               LISTEN      764/named
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      764/named
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      706/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      801/sshd: /usr/sbin
tcp        0      0 127.0.0.1:953           0.0.0.0:*               LISTEN      764/named
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/init
tcp6       0      0 :::22                   :::*                    LISTEN      801/sshd: /usr/sbin
tcp6       0      0 :::111                  :::*                    LISTEN      1/init
udp        0      0 10.0.0.128:53           0.0.0.0:*                           764/named
udp        0      0 10.0.0.128:53           0.0.0.0:*                           764/named
udp        0      0 127.0.0.1:53            0.0.0.0:*                           764/named
udp        0      0 127.0.0.1:53            0.0.0.0:*                           764/named
udp        0      0 127.0.0.53:53           0.0.0.0:*                           706/systemd-resolve
udp        0      0 10.0.0.128:68           0.0.0.0:*                           704/systemd-network
udp        0      0 0.0.0.0:111             0.0.0.0:*                           1/init
udp6       0      0 :::111                  :::*                                1/init
```

I'll see if I run the dev branch later today.

**Comment by geeknik** [comment]
Your netstat output leads me to think it is listening on local IP only. For example, I correctly see a 0.0.0.0:22 for your SSH port but I don't see an 0.0.0.0:25, 0.0.0.0:53, 0.0.0.0:80, or 0.0.0.0:443, for your Interactsh.

**Comment by geeknik** [comment]
Try passing the `-ip` flag with the IP of your server and see if that makes a difference?

**Comment by bluesm866** [comment]
Hello @geeknik,
Running the dev branch either using -domain or -ip I am getting this output:
```
sudo ./interactsh-server -ip 168.138.128.154
[INF] Listening with the following services:
        SMTP :25
        DNS :53
        HTTP :80
[ERR] Could not serve dns on port 53: listen udp 0.0.0.0:53: bind: address already in use
[FTL] The DNS service has unexpectedly stopped
```

Only after stopping _BIND9_ and _systemd-resolved_ services I was able to start _Interactsh Server_ with -ip (-domain would not work, since I killed my BIND9 dns server).

Is _Interactsh Server_ not supposed to run on the same machine as my dns server? Does it work as a dns server itself? If so, where should I configure it, with my registers, zones, pointers, etc?

**Comment by geeknik** [comment]
i'm not running bind, i handle all of the dns stuff through my host. 

ns1.domain.tld is an A record pointed at the IP of my host's ns1
ns2.domain.tld is an A record pointed at the IP of my host's ns2
ns3.domain.tld is an A record pointed at the IP of my host's ns3

domain.tld is an A record for the IP assigned to my VM by my host

My command line is something like `interactsh-server -ip x.x.x.x -domain xxx.tld -hostmaster  email@domain`

**Comment by bluesm866** [comment]
Additionally, here is the output using -debug flag:
```
 sudo ./interactsh-server -domain bm866.cc -debug
[ERR] Could not serve dns on port 53: listen udp 168.138.128.154:53: bind: cannot assign requested address
[WRN] An error occurred while applying for an certificate, error: could not generate new certs: error creating new account: acme: error code 429 "urn:ietf:params:acme:error:rateLimited": Error creating new account :: too many registrations for this IP: see https://letsencrypt.org/docs/rate-limits/
[WRN] Could not generate certs for auto TLS, https will be disabled
2021/12/28 00:24:06 Listening on DNS, SMTP and HTTP ports
[ERR] Could not serve http: listen tcp 168.138.128.154:80: bind: cannot assign requested address
[ERR] Could not serve smtp on port 587: listen tcp 168.138.128.154:587: bind: cannot assign requested address
[ERR] Could not serve smtp on port 25: listen tcp 168.138.128.154:25: bind: cannot assign requested address
```
Ports being used:
```
 sudo netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 10.0.0.128:53           0.0.0.0:*               LISTEN      3180/named
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      3180/named
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      3161/systemd-resolv
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      832/sshd: /usr/sbin
tcp        0      0 127.0.0.1:953           0.0.0.0:*               LISTEN      3180/named
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/init
tcp6       0      0 :::22                   :::*                    LISTEN      832/sshd: /usr/sbin
tcp6       0      0 :::111                  :::*                    LISTEN      1/init
udp        0      0 10.0.0.128:53           0.0.0.0:*                           3180/named
udp        0      0 10.0.0.128:53           0.0.0.0:*                           3180/named
udp        0      0 127.0.0.1:53            0.0.0.0:*                           3180/named
udp        0      0 127.0.0.1:53            0.0.0.0:*                           3180/named
udp        0      0 127.0.0.53:53           0.0.0.0:*                           3161/systemd-resolv
udp        0      0 10.0.0.128:68           0.0.0.0:*                           727/systemd-network
udp        0      0 0.0.0.0:111             0.0.0.0:*                           1/init
udp6       0      0 :::111                  :::*                                1/init

```

**Comment by ehsandeep** [comment]
> Is Interactsh Server not supposed to run on the same machine as my dns server? Does it work as a dns server itself? If so, where should I configure it, with my registers, zones, pointers, etc?

Yes, Interactsh server runs / required it's own DNS server so you wanted to host this server on fresh box with no existing service running on it or stop them before running interactsh server.

**Comment by bluesm866** [comment]
Hello @geeknik and @ehsandeep,
Thanks for the attention. I created a second VM and on BIND9 of the first VM I pointed my records to my second VM running Interactsh Server.

It would be a neat feature for the future if we could configure Interactsh Server as a DNS server in itself (or maybe integrate it with BIND9, I don't know if it is technically possible though).
