### ISSUE TITLE
[Feature] Printing the full Hostname

### ISSUE THREAD

**Issue by shubhack-repo** [projectdiscovery/interactsh#15]
I see that you have implemented the burp collaborator feature of wildcard mapping to the source collaborator address.

Example : <anything>.<Unique-ID>.interact.sh -> <Unique-ID>.interact.sh

That's great feature . But it would be great if you print this whole <anything>.<unique-ID>.interact.sh on the terminal whenever a query triggered without verbose flag. Because verbose flag print many unwanted information (in case of DNS queries).

Example:
```
if we ping anything.<UNIQUE-ID>.interact.sh
And the interactsh client shows ( without verbose flag)
[<UNIQUE-ID>] Recieved DNS interaction (A) from <ORIGIN-IP> at <TIMESTAMP>
```
So the **anything** is omitted , which is sometimes important during Bug Bounties.

**Comment by ehsandeep** [comment]
```
curl http://testing.c2ki07i0kl1ui690o06gcnw1y8ayyyyyn.interact.sh
```

Current behavior:-

```sh
interactsh-client 

[INF] c2ki07i0kl1ui690o06gcnw1y8ayyyyyn.interact.sh
[c2ki07i0kl1ui690o06gcnw1y8ayyyyyn] Recieved DNS interaction (A) from 103.195.200.42 at 2021-22-22 15:16
[c2ki07i0kl1ui690o06gcnw1y8ayyyyyn] Recieved DNS interaction (A) from 172.217.34.130 at 2021-22-22 15:16
[c2ki07i0kl1ui690o06gcnw1y8ayyyyyn] Recieved HTTP interaction from 103.22.143.108 at 2021-22-22 15:16
```

Expected behavior:-

```sh
interactsh-client 

[INF] c2ki07i0kl1ui690o06gcnw1y8ayyyyyn.interact.sh
[testing.c2ki07i0kl1ui690o06gcnw1y8ayyyyyn] Recieved DNS interaction (A) from 103.195.200.42 at 2021-22-22 15:16
[testing.c2ki07i0kl1ui690o06gcnw1y8ayyyyyn] Recieved DNS interaction (A) from 172.217.34.130 at 2021-22-22 15:16
[testing.c2ki07i0kl1ui690o06gcnw1y8ayyyyyn] Recieved HTTP interaction from 103.22.143.108 at 2021-22-22 15:16
```

**Comment by ehsandeep** [comment]
@shubhack-repo Now supported in [v0.0.4](https://github.com/projectdiscovery/interactsh/releases/tag/v0.0.4) release, thank you.

**Comment by shubhack-repo** [comment]
Hello @ehsandeep , i don't see the full fqdn output in latest release 0.0.4 .

![Screenshot 2021-08-10 10:04:09](https://user-images.githubusercontent.com/55850362/128808747-c88cf179-37a9-4d0c-af23-bac1885cf25a.png)


You can see that it doesn't output the full fqdn.

**Comment by Mzack9999** [comment]
@shubhack-repo The change should be reflected on the hosted version within today. Thanks!

**Comment by ehsandeep** [comment]
@shubhack-repo it was supported for self-hosted version, as we restarted the server, now it should be supported for cloud-hosted version as well.

```
interactsh-client 

    _       __                       __       __  
   (_)___  / /____  _________ ______/ /______/ /_ 
  / / __ \/ __/ _ \/ ___/ __ '/ ___/ __/ ___/ __ \
 / / / / / /_/  __/ /  / /_/ / /__/ /_(__  ) / / /
/_/_/ /_/\__/\___/_/   \__,_/\___/\__/____/_/ /_/ v0.0.4

		projectdiscovery.io

[INF] Listing 1 URL for OOB Testing
[INF] c4938t9e0086hqr0t680crjde7eyyyyyn.interact.sh
[test.c4938t9e0086hqr0t680crjde7eyyyyyn] Received DNS interaction (A) from 103.195.200.42 at 2021-08-10 08:10:36
[test.c4938t9e0086hqr0t680crjde7eyyyyyn] Received DNS interaction (A) from 172.253.226.100 at 2021-08-10 08:10:36
[test.c4938t9e0086hqr0t680crjde7eyyyyyn] Received HTTP interaction from 103.22.142.207 at 2021-08-10 08:10:36
[test.c4938t9e0086hqr0t680crjde7eyyyyyn] Received HTTP interaction from 103.22.142.207 at 2021-08-10 08:10:37
```

**Comment by shubhack-repo** [comment]
Thanks for the feature . 😀
