### ISSUE TITLE
Allow use of base domain (or custom sub-domain) for self-hosted servers

### ISSUE THREAD

**Issue by geeknik** [projectdiscovery/interactsh#17]
Hello and thank you for this awesome tool, it will surely come in handy during our testing.

The current behavior of interactsh is to create a randomized subdomain like `c282n3l3djgbti5v595gcnenzdoyyyyyn.domain.tld`, which is fine and all, however, we have a pretty nice 4 x 2 domain and we feel that smaller payloads are the best, so could you allow the use of the base domain and/or customized sub-domains for self-hosted servers in addition to the randomized subdomains? 

Edited to ask for customized sub-domains option as well. 👍🏻

**Comment by ResistanceIsUseless** [comment]
I second this. I've been using the following script - https://github.com/JuxhinDB/OOB-Server to run my own. It works good enough but something that is more than just a setup script with active dev by project discovery gets my vote.

**Comment by Ice3man543** [comment]
@geeknik @ResistanceIsUseless this is possible, but will generate lot of noise. One thing could be to add custom subdomains, so you can specify a short sub, like target.<self-hosted-server> and it will listen for that subdomain. This cannot be enabled for public servers due to collision issues, but maybe something that self hosted servers can support?

**Comment by rst10124492** [comment]
+1 for custom subdomains, it allows management of interactable urls to be easier

**Comment by ResistanceIsUseless** [comment]
FYI doing something.c2c3w5gyedf00006158ggbgb6nayyyyyb.interact.sh works
fine. You can utilize this by adding a unique value for the field-domain
you're testing. For example, x-forwarded-subdomain. You can automate
testing a big list by bash loop:

cat subdomains.txt | while IFS= read -r line; do httpx -H "Host:
hst-$line.c2c3w5gyedf00006158ggbgb6nayyyyyb.interact.s "; done

;; opcode: QUERY, status: NOERROR, id: 586;; flags: cd; QUERY: 1,
ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1;; QUESTION
SECTION:;something.c2c3w5gyedf00006158ggbgb6nayyyyyb.interact.sh.	IN	
AAAA;; ADDITIONAL SECTION:;; OPT PSEUDOSECTION:; EDNS: version 0;
flags: do; udp: 512

**Comment by ResistanceIsUseless** [comment]
The thing i would like to see is a self hosted solution using my personal
domain. Obviously this would require someone to 1. Own a domain, 2. Setup
the correct name server entries with their Domain Registrar. Then it would
be nice to have interactsh run on your VPC or whatever so you could have
your own personalized uniquestring.mydomain.tld with the interactsh UI
running locally (either on 127.0.0.1 or password protected). That's what
I'm referring to when i say custom self hosted method of interactsh.

**Comment by ehsandeep** [comment]
@geeknik @ResistanceIsUseless @rst10124492 @Ice3man543 ^^

This is now enabled with `root-tld` flag that enables **wildcard** interaction support, to ensure the security `root-tld` flag comes with the implicit use of token if not specified manually.

Interactsh Server:

```
./interactsh-server -domain example.com -hostmaster admin@example.com -ip X.X.X.X -listen-ip X.X.X.X -root-tld
```

Visiting canyouseeme.example.com will result into :-

Client:

```
./interactsh-client -token XXXX

[canyouseeme.example.com.] Received DNS interaction (A) from 49.45.31.132 at 2021-08-28 20:47:36
[canyouseeme.example.com.] Received DNS interaction (A) from 49.45.31.132 at 2021-08-28 20:47:36
[canyouseeme.example.com] Received HTTP interaction from 49.36.108.46 at 2021-08-28 20:47:36
[canyouseeme.example.com] Received HTTP interaction from 49.36.108.46 at 2021-08-28 20:47:36
[canyouseeme.example.com] Received HTTP interaction from 49.36.108.46 at 2021-08-28 20:47:36
```
