### ISSUE TITLE
Add ability to restrict access to self-hosted servers

### ISSUE THREAD

**Issue by geeknik** [projectdiscovery/interactsh#18]
Hello, currently there is no protection against allowing anyone to connect to a self-hosted hosted if they know the URL. Please add some sort of authentication mechanism so that servers aren't abused. Maybe something like this?
```
$ interactsh-server -auth "$(uuid-gen)"
$ interactsh-client -auth "generated-uuid" -url https://domain.tld
```
 Thank you.

**Comment by dogasantos** [comment]
+1

**Comment by ehsandeep** [comment]
@geeknik @dogasantos this is now supported in dev branch and ready to use for self-hosted server, example used shared here - https://github.com/projectdiscovery/interactsh/pull/54#pullrequestreview-713915366

**Comment by ehsandeep** [comment]
Now supported in [v0.0.4](https://github.com/projectdiscovery/interactsh/releases/tag/v0.0.4) release, thanks for suggesting this feature request. @geeknik @dogasantos ^^

1. **Auto-generated** token with `auth` flag.

```
./interactsh-server -auth
```

2. **Custom** token generation with `token` flag

```
./interactsh-server -token my_token
```

and interaction can be retrieved with the following example:-

```
./interactsh-client -token TOKEN_HERE
```
