### ISSUE TITLE
IpAddress is set to ListenIpAddress (causing issues on servers behind NAT)

### ISSUE THREAD

**Issue by NDrong** [projectdiscovery/interactsh#200]
### Current Behavior:  `IpAddress` is set to `ListenIpAddress`
Since the latest release (v1.0.0), [`IpAddress` is being set to `ListenIpAddress`](https://github.com/projectdiscovery/interactsh/blob/main/pkg/options/server_options.go#L37) causing issues on servers operating behind NAT. This bug was not present is previous releases.

In other words: the argument passed to `-listen-ip` is also passed to `-ip` (overwriting any argument originally passed to `-ip`).

### Expected Behavior: IpAddress is set to IpAddress
IpAddress should be set to the value passed to `-ip` and ListenIpAddress should be set to the value passed to `-listen-ip`.

### Steps To Reproduce:

1. Set `-ip` to some value and `-listen-ip` to another value.
2. Notice that the value passed to `-listen-ip` is returned as the external ip address (instead of the value passed to`-ip` as expected from the docs and in accordance with previous behavior).

I'll open a PR with a bug fix for this shortly :).

**Comment by ehsandeep** [comment]
@NDrong thank you flagging and fixing this, fix is now pushed in latest release.
