### ISSUE TITLE
optional short ids support

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/interactsh#204]
### Discussed in https://github.com/projectdiscovery/interactsh/discussions/118

<div type='discussions-op-text'>

<sup>Originally posted by **webca7** December  8, 2021</sup>

You have a self-hosted instance, there's still a lot of different users to use this. Since Chinese-owned `dnslog.cn` only use `6` char as second-level prefix, it still works well, they have about **1B** users. We don't really need such long prefix since only `[A-Z][a-z][0-9]{6}` has about `(26+26+10)^6`= **568,0023,5584** possibilities.
</div>

-------

Boolean flag (disabled as default)

```yaml
   -cidl, -correlation-id-length int        Length of the correlation id preamble (default 20)
   -cidn, -correlation-id-nonce-length int  Length of the correlation id nonce (default 13)
```

Example run of interactsh-client with short-id

```console
./interactsh-client -cidl 4 -cidn 6 -n 10 -s SELF_HOSTED_SERVER

    _       __                       __       __  
   (_)___  / /____  _________ ______/ /______/ /_ 
  / / __ \/ __/ _ \/ ___/ __ '/ ___/ __/ ___/ __ \
 / / / / / /_/  __/ /  / /_/ / /__/ /_(__  ) / / /
/_/_/ /_/\__/\___/_/   \__,_/\___/\__/____/_/ /_/ v1.0.2-dev

		projectdiscovery.io

[INF] Listing 10 payload for OOB Testing
[INF] c8msgn4r9t.SELF_HOSTED_SERVER
```

**Comment by junero88** [comment]
After PR #210, is the short-id feature working?

```
> interactsh-client -cidl 4 -cidn 6 -n 1 -v 

    _       __                       __       __
   (_)___  / /____  _________ ______/ /______/ /_
  / / __ \/ __/ _ \/ ___/ __ '/ ___/ __/ ___/ __ \
 / / / / / /_/  __/ /  / /_/ / /__/ /_(__  ) / / /
/_/_/ /_/\__/\___/_/   \__,_/\___/\__/____/_/ /_/ v1.0.2-dev

                projectdiscovery.io

[INF] Listing 1 payload for OOB Testing
[INF] c8poe43r4h.oast.pro
```

If I access that subdomain via HTTP, I receive no output at the `interactsh-client`

**Comment by ehsandeep** [comment]
@junero88 this is optional feature support for **self-hosted** servers and not enabled for public interactsh servers.
