### ISSUE TITLE
custom config file input support for interactsh client/server

### ISSUE THREAD

**Issue by the-securitytest** [projectdiscovery/interactsh#251]
I would love to see an option to specify a config file to be able to start and stop and further control it via systemd.

The config file option is not available and to pass all the configuration options to the start command is a bit overkill. 
I couldn't get it working through systemd with screen; since it can't find the /root/.config/interactsh-server/config.yaml or doesn't know it should search for it. 

------

custom config file input support for [interactsh-client](https://github.com/projectdiscovery/interactsh/tree/main/cmd/interactsh-client)
```yaml
   -c, -config string                flag config file for interactsh-client (default "$HOME/.config/interactsh-client/config.yaml")
```

custom config file input support for [interactsh-server](https://github.com/projectdiscovery/interactsh/tree/main/cmd/interactsh-server)

```yaml
   -c, -config string                flag config file for interactsh-server (default "$HOME/.config/interactsh-client/config.yaml")
```

**Comment by Ice3man543** [comment]
Also introduce a `--version` flag to show current version for interactsh-client,server.

**Comment by ehsandeep** [comment]
@the-securitytest `-config` flag is now supported in the **dev** version to specify the config file from custom location for both client/server.

**Comment by ehsandeep** [comment]
@the-securitytest this is now supported with the latest version of the project.
