### ISSUE TITLE
Is the -root-tld flag still working ? 

### ISSUE THREAD

**Issue by greckko** [projectdiscovery/interactsh#268]
./interactsh-server -domain example.com -hostmaster admin@example.com -ip X.X.X.X -listen-ip X.X.X.X -root-tld

```flag provided but not defined: -root-tld```

https://github.com/projectdiscovery/interactsh/issues/17

Is it now enabled by default ?

**Comment by ehsandeep** [comment]
@greckko flag name is updated with below:

```
   -wc, -wildcard          enable wildcard interaction for interactsh domain (authenticated)
```
