### ISSUE TITLE
[Feature] Burp suite extension for interactsh client

### ISSUE THREAD

**Issue by vay3t** [projectdiscovery/interactsh#31]
Maybe it is not very necessary, but if it would be something interesting, a client for burpsuite (community), it is necessary to take into account that it would be an extra maintenance, no wonder they reject the idea. but still I comment

**Comment by wdahlenburg** [comment]
@vay3t Can you test out https://github.com/wdahlenburg/interactsh-collaborator?

**Comment by ehsandeep** [comment]
Working very well @wdahlenburg, thanks a lot for making and sharing this with everyone 💚

**Comment by vay3t** [comment]
of course @wdahlenburg

**Comment by vay3t** [comment]
@wdahlenburg @ehsandeep  It works spectacular. Are you thinking of joining the project to projectdiscovery or giving it support?

**Comment by ehsandeep** [comment]
thanks for confirming, closing this issue now. We will be linking this in the readme as well with instruction details.

**Comment by wdahlenburg** [comment]
> @wdahlenburg @ehsandeep It works spectacular. Are you thinking of joining the project to projectdiscovery or giving it support?

Thanks! I'm going to hold on to it for the near future for support. Once it's a bit more robust, I'd love to see if Portswigger will accept it in the BApp store.

From a longer term perspective it may make sense for PD to own it (if they want to), but it really depends on how much activity there is on the repo.
