### ISSUE TITLE
match/filter interactions support

### ISSUE THREAD

**Issue by kiriknik** [projectdiscovery/interactsh#313]
If you run a dedicated interact-sh server, and then attach to this server interact-sh client, client show all request (include ns1.domain.com, etc)
Please add flag to show only generated domain in client part

Cli flag:

```yaml
   -m, -match       match interaction based on the specified pattern
   -f, -filter      filter interaction based on the specified pattern
```

Example:

```bash
# Running client with filtering specified subdomains
./interactsh-client -s hackwithautomation.com -f mail,smtp,ns
./interactsh-client -s hackwithautomation.com -f filter.txt
```

```bash
# Running client with matching specified subdomains
./interactsh-client -s hackwithautomation.com -m log4j,cb9u25bin56365jabbe0b6ouneuw6nxhe
./interactsh-client -s hackwithautomation.com -m match.txt
```

**Comment by ehsandeep** [comment]
@kiriknik just to be sure, you were running the server in `-wildcard` mode, right?

**Comment by kiriknik** [comment]
Yes - to check all domains)
maybe you can add flag (like --show-only-registered) - to show only generated domain?)

**Comment by Mzack9999** [comment]
@ehsandeep `-wildcard` seems to be working as expected here. I think a better option would be adding `--show-only/match/filter *.xxxx.yyy.zzzz,*.aaa.bbb`. What do you think?

**Comment by ehsandeep** [comment]
@Mzack9999 updated the issue with the suggested flag and example.
