### ISSUE TITLE
cloud metadata dns record bugfix + configurable yaml file to set dns records

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/interactsh#333]
### Interactsh version:
dev

### Current Behavior:
[Preconfigured subdomain](https://github.com/projectdiscovery/interactsh#cloud-metadata) pointing to root domain IP instead of defined one.
 
### Expected Behavior:
dns records pointing to configured records.

### Steps To Reproduce:

```
./interactsh-server -d hackwithautomation.com
```

```console
$ host aws.hackwithautomation.com
aws.hackwithautomation.com has address 157.230.223.165
Host aws.hackwithautomation.com not found: 2(SERVFAIL)
aws.hackwithautomation.com mail is handled by 1 mail.hackwithautomation.com.

$ host alibaba.hackwithautomation.com
alibaba.hackwithautomation.com has address 157.230.223.165
Host alibaba.hackwithautomation.com not found: 2(SERVFAIL)
alibaba.hackwithautomation.com mail is handled by 1 mail.hackwithautomation.com.
```

### Anything else:

Configurable yaml config file can be used instead of [hardcoded records](https://github.com/projectdiscovery/interactsh/blob/eba17e4a0ed4899363fed36468ec0c63548b350b/pkg/server/dns_server.go#L179-L185) allowing users extend and set arbitrary records with custom interactsh server.

```yaml
# dns block is used to configure arbitrary A record for an arbitrary subdomain
# for the domain used with interactsh server.
# format: subdomain: a record
a: 
  alibaba: 100.100.100.200
  aws: 169.254.169.254
```

**Comment by brenocss** [comment]
Also would be great to implement something like this https://github.com/projectdiscovery/interactsh/discussions/317 and this https://github.com/projectdiscovery/interactsh/discussions/315
```python
$ host ip-8.8.8.8.cbaqgsmt9s6s7jduvmtgik6jdmwb6pr5r.oast.site
ip-8.8.8.8.cbaqgsmt9s6s7jduvmtgik6jdmwb6pr5r.oast.site has address 8.8.8.8
```
```python
$ host -t A make-1.2.3.4-rebind-169.254-169.254-rr.1u.ms
make-1.2.3.4-rebind-169.254-169.254-rr.1u.ms has address 1.2.3.4
$ host -t A make-1.2.3.4-rebind-169.254-169.254-rr.1u.ms
make-1.2.3.4-rebind-169.254-169.254-rr.1u.ms has address 169.254.169.254
```
