### ISSUE TITLE
Show the help menu if an inexistent flag is provided to interactsh-server

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/interactsh#357]
Actual:
![image](https://user-images.githubusercontent.com/13679401/185374710-78f6fdd7-1a27-46e2-9e8d-38499fe25beb.png)

Expected similarly to `interactsh-client`:
![image](https://user-images.githubusercontent.com/13679401/185374790-1cb75114-509a-49bf-aefa-e3ababddf4bf.png)

**Comment by ehsandeep** [comment]
@forgedhallpass client and server have the same behavior in the `main` branch and are updated in `dev` branch with intentional change as a result of https://github.com/projectdiscovery/goflags/issues/62
