### ISSUE TITLE
SMB interactions are received but not displayed to the client

### ISSUE THREAD

**Issue by leesoh-bf** [projectdiscovery/interactsh#360]
### Interactsh version:

v1.0.6

### Current Behavior:

After launching the self-hosted server and verifying that the server launches correctly, I initiate an SMB connection to the server. The connection is successful and DNS interactions are received by the client, but no SMB interaction is shown.

### Expected Behavior:

A SMB connection is shown in the client.

### Steps To Reproduce:

1. Launch interactsh-server using `./interactsh-server -domain <domain> -token <token> -smb`, ensuring `smb_server.py` is available.
2. Launch the client using `./interactsh-client -server <domain> -token <token>`.
3. On a second host, initiate an SMB connection. On Linux, you can do `smbclient -L <payload hostname>`.
4. Observe that DNS interactions are shown, but no SMB interaction appears.
5. Close the server and the client.
6. Repeat steps 1-4 but add `-debug` to the server.
7. Observe that the SMB connection is shown in the debug log.

**Comment by ehsandeep** [comment]
@leesoh-bf should be fixed in dev version with https://github.com/projectdiscovery/interactsh/pull/424

**Comment by leesoh-bf** [comment]
Thanks @ehsandeep !!
