### ISSUE TITLE
Add ability to redirect to another host

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/interactsh#362]
I would like to redirect to another host or protocol.

As example for SSRF: http://localhost -> 403; interactsh host -> 200

If we can redirect our host to http://localhost, we can bypass.

Also for protocol, http -> 200; sftp -> 403

**Comment by ehsandeep** [comment]
@akincibor this will be handled as part of https://github.com/projectdiscovery/interactsh/issues/364 that let you set arbitrary status code and header for redirect.
