### ISSUE TITLE
interactsh server integration test

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/interactsh#379]
### Please describe your feature request:
A GitHub workflow to ensure interactsh server is able to run in different/available environments upon each change in server code.

**Comment by Mzack9999** [comment]
@ehsandeep we need to identify the scenarios we want to cover, for example:
- Target Operative Systems
    - [ ] OSX
    - [ ] Windows
    - [ ] Linux
- Minimum set operations required for successful run:
    - [ ] Certificate loading/renewal
    - [ ] Services that must start: http, dns, smtp

**Comment by Mzack9999** [comment]
Abandoned - The set of operations required can't be performed on a GH worker as it requires public facing ip for certificate reneval and/or other custom scenarios
