### ISSUE TITLE
Feature request: Integration of the DNS-Analysis-Server

### ISSUE THREAD

**Issue by sfunkernw** [projectdiscovery/interactsh#390]
Feature request: Integration of the DNS-Analysis-Server

Wouldn't it be nice, if we could integrate this https://github.com/The-Login/DNS-Analysis-Server as functionality of the interactsh server?

**Comment by Mzack9999** [comment]
I think this is out of scope of the project, since interactsh is more about detecting OOB interactions for many protocols, not producing full security compliance report of dns setup - I'm closing this as not planned for the time being
