### ISSUE TITLE
Add documentation about how to run interactsh behind reverse proxy

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/interactsh#395]
### Please describe your feature request:
As a user, I would like to know if running and configuring interactsh easily behind a reverse proxy is possible. If this is feasible, the documentation should be updated accordingly.
Another suggestion might be to provide setup scripts/recipes for various cloud environments/operators to deploy the service quickly.

### Describe the use case of this feature:
Standard http/https ports might be busy with default HTTP daemon, and the possibility of running interactsh on a subdomain behind the reverse proxy would allow using the same domain for all the services.

original request: @PatrikFehrenbach

**Comment by af001** [comment]
You should be able to pretty easily, but you would need to use something like nginx to `proxy_pass` traffic back to the container or standalone binary. You would also have to adjust the listening ports on the interactsh_server. Example:

Nginx accept TCP port 389 and send to interactsh_server port 10389
```
stream {
    server {
        # Listen TCP 389
        listen 389;
        proxy_pass localhost:10389;
    }
}
```

Nginx accept port 443 and sent to interactsh_server port 10443

```
http {
      server {
            # HTTPS terminates here
            listen  443 ssl;
            server_name  site.mydomain.com;

            ssl_certificate             /etc/nginx/site.mydomain.com.pem;
            ssl_certificate_key     /etc/nginx/site.mydomain.com.key;

            location / {
                proxy_pass                   https://localhost:10443/;
                proxy_set_header        Host               $host;
                proxy_set_header        X-Real-IP       $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Proto $scheme;
            }        
      }
}
```

For other web applications that may use port 443 or port 80, you can add an additional `location /`, such as:
```
            location / {
                proxy_pass                   https://localhost:10443/;
                proxy_set_header        Host               $host;
                proxy_set_header        X-Real-IP       $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Proto $scheme;
            }     

            location /myotherapp/ {
                root   /var/www/html;
                index  index.html index.htm;
            }

            location /myotherotherapp/ {
                root   /var/www/html2;
                index  index.html index.htm;
            }
```

For SMTP, it would be similar to LDAP:
```
stream {
    server {
        listen 25;
        proxy_pass localhost:10025;
    }
}
```
