### ISSUE TITLE
could not make register request

### ISSUE THREAD

**Issue by secureinfo42** [projectdiscovery/interactsh#408]
Hello :)

My env is zsh/macOS Monterey, I disabled firewalls, and I can't run `interact-sh`, I have the error : 

```
[VER] Could not register to oast.site: could not make register request: POST http://oast.me/register giving up after 1 attempts: Post "http://oast.me/register": dial tcp: lookup oast.me on [::1]:53: read udp [::1]:64638->[::1]:53: read: connection refused, retrying with remaining
```

NB : it works on a Linux

**Comment by ehsandeep** [comment]
For some reason, IPv6 interface is being picked on your mac system, so switching to IPv4 should fix the issue, supporting is IPv6 is being tracked here - https://github.com/projectdiscovery/interactsh/issues/307
