### ISSUE TITLE
Implement pluggable persistent storage in interactsh-client

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/interactsh#456]
### Please describe your feature request:
Interactsh-client CLI should be able to persist/export interactions to storage layers such as db, elasticsearch, etc

**Comment by dogancanbakir** [comment]
IMO, the supported JSON output is compatible and can be easily integrated into any system. However, do you still think there is a need for additional integrations such as db, elasticsearch, etc?

**Comment by dogancanbakir** [comment]
I'm closing -upon discussion- as not planned; since we believe the JSON output to stdout/file covers most use cases.
