### ISSUE TITLE
[Feature] SMB Listener

### ISSUE THREAD

**Issue by yosignals** [projectdiscovery/interactsh#48]
Sometimes I use Responder just to collect incoming hashes from AD/Windows integrated apps
it's not a big inconvenience for me to just configure it to listen from my private hosted interactsh-server, but it would be a nice to have a built in listener to register/capture/note those events dont you think ?

**Comment by Mzack9999** [comment]
Related issues:
- https://github.com/projectdiscovery/interactsh/issues/9
- https://github.com/projectdiscovery/interactsh/issues/7
