### ISSUE TITLE
Building docker image Interactsh Server still failed

### ISSUE THREAD

**Issue by Bisstocuz** [projectdiscovery/interactsh#499]
### Interactsh version:
`v1.1.0` and `v1.1.1`

### Current Behavior:
See https://github.com/projectdiscovery/interactsh/actions/runs/4393696369

### Expected Behavior:
Build and successfully upload to Docker Hub.

### Steps To Reproduce:
None

### Anything else:
It seems that need a environment based on `arm/v7` arch to test. (related PR #485)

**Comment by Bisstocuz** [comment]
[This](https://cryptography.io/en/latest/installation/#supported-platforms) is `cryptography` support systems, it's better to remove `linux/arm/v7` support.

I tried build `linux/arm/v7` on `amd64` with `qemu` but throws `Out of Memory` exception.

**Comment by ehsandeep** [comment]
This now fixed - https://github.com/projectdiscovery/interactsh/actions/runs/4436828209/jobs/7785744725 @Bisstocuz
