### ISSUE TITLE
[issue] Broken dependency smtpd

### ISSUE THREAD

**Issue by Skyr** [projectdiscovery/interactsh#56]
**Describe the bug**
Project depends on github.com/prologic/smtpd, but https://github.com/prologic/smtpd results in a 404, repo seems gone.
Error occurred when trying to open the Nuclei source in GoLand on a pristine machine.

**Version**
Nuclei: Trunk of master (currently at 84244b5)
Interactsh: Seems to be present in trunk, too

**Screenshot of the error or bug**
```
go list -modfile=nuclei/v2/go.mod -m -json -mod=mod all #gosetup
go: github.com/projectdiscovery/interactsh@v0.0.3 requires
	github.com/prologic/smtpd@v0.0.0-20210126001904-0893ad18168e: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in ~/go/pkg/mod/cache/vcs/65b3100cfa8e2061b6047e41aaceb4a1e850f70977a718cfde5bd0e009bb0722: exit status 128
```

**Comment by Skyr** [comment]
I'm not a Go person, so I'm not used to some probably Go-specific routines. I had a look at https://pkg.go.dev/git.mills.io/prologic/smtpd - they refer to https://git.mills.io/prologic/smtpd/ as their repository... and indeed, the latest commit (2 weeks ago) states that the project has moved away from GitHub to Mill. So it's just a matter of updating the reference, I guess :-)

**Comment by Mzack9999** [comment]
@Skyr Thanks for reporting the issue! This will be fixed asap.

**Comment by ehsandeep** [comment]
@Skyr Thanks for reporting this; the fix has since been merged into the dev branch; for the time being, you can alter the nuclei mod file to point to the interactsh dev branch.

**Comment by ehsandeep** [comment]
@Skyr we pushed a new release for - https://github.com/projectdiscovery/interactsh/releases/tag/v0.0.4, thanks for reporting.
