### ISSUE TITLE
use of closed network connection!!

### ISSUE THREAD

**Issue by 0xhunster** [projectdiscovery/interactsh#597]
I don't know why showing this issue!!

![image](https://github.com/projectdiscovery/interactsh/assets/46501627/bb54103c-39fb-4657-ba03-af75ed71caa4)

![image](https://github.com/projectdiscovery/interactsh/assets/46501627/b03e25d4-4ca6-424b-b901-8373e5f34da9)

**Comment by Mzack9999** [comment]
This should be already fixed with https://github.com/projectdiscovery/interactsh/pull/531 - It's due to random eviction in the server cache
