### ISSUE TITLE
Not able to run Interachsh -server on Digital Ocean Droplet. 

### ISSUE THREAD

**Issue by Shri1610** [projectdiscovery/interactsh#71]
Hi team,

I have created a DO Debain Droplet and installed a Floating IP added the configuration as said under the self hosted instance guide. Can anyone please help?

![Screenshot_2021-08-13_10-41-25](https://user-images.githubusercontent.com/28747114/129374336-a092f2c8-52a1-4859-a75d-0e0f3010882c.png)

**Comment by Shri1610** [comment]
Pinging the website resolves to the IP address but doesnt give any response

**Comment by ehsandeep** [comment]
@Shri1610 as per the screenshot, this doesn't look an issue, as the server is running, you should be able to see the logs/interaction using `interactsh-client`, server doesn't display/log any data as per design.

If something is unclear, feel free to jump in discord server - https://discord.gg/projectdiscovery

**Comment by geeknik** [comment]
I'm using `interactsh-server` on Digital Ocean without issue but I'm also not using a Floating IP address. Not sure what the need for that is?

**Comment by Shri1610** [comment]
@geeknik : You mean to say that the public which is provided By DO is the one you are using right?

**Comment by geeknik** [comment]
> @geeknik : You mean to say that the public which is provided By DO is the one you are using right?

Correct, am just using whatever IP they assigned to the VPS. 👍🏻

**Comment by Shri1610** [comment]
Will Try and Check
Thanks for the input

**Comment by Shri1610** [comment]
@geeknik My Understanding of Floating IP was wrong it seems. I turned it on by mistake and used the same even in DNS Settings. Try your recommended settings now. will keep you posted

**Comment by Shri1610** [comment]
It worked. Thanks a lot for your help.

**Comment by geeknik** [comment]
You're welcome! 👍🏻
