### ISSUE TITLE
Make -http-directory work with -dynamic-response

### ISSUE THREAD

**Issue by ounissi-zakaria** [projectdiscovery/interactsh#741]
### Please describe your feature request:
Would it be possible (or a good idea?) to make http-directory files work with -dynamic-response headers/status. example: 
request ==> oast.fun/s/evil-image.png?header=content-type:image/svg%2Bxml&status=500

### Describe the use case of this feature:
- Sometimes when the body of the response is big i can't use dynamic response normally and include it in the url
- Having to write response then url encoding it then copying it to the url is annoying

I forked the repo and made a change for this changes to work. But I am not sure if it's the best approach. you can check the changes [here](https://github.com/projectdiscovery/interactsh/compare/main...ounissi-zakaria:interactsh:main)

**Comment by dogancanbakir** [comment]
@ounissi-zakaria, Thanks for taking the initiative to open up this issue and your efforts to make it happen! Could you please raise a PR and let us review it?
