### ISSUE TITLE
import err：unrecognized import path "aead.dev/minisign"

### ISSUE THREAD

**Issue by Nyx2022** [projectdiscovery/interactsh#756]
### Interactsh version:
1.1.8

### Current Behavior:

when i import this lib  with goland,the error occurs:
go: github.com/minio/selfupdate@v0.6.1-0.20230907112617-f11e74f84ca7 requires
	aead.dev/minisign@v0.2.0: unrecognized import path "aead.dev/minisign": parse https://aead.dev/minisign?go-get=1: no go-import meta tags ()

### Expected Behavior:

imported successful

### Steps To Reproduce:
import it as a new lib

### Anything else:
![image](https://github.com/projectdiscovery/interactsh/assets/51039208/8a4473f2-a32c-4bb5-8f31-09ab38bf2463)

**Comment by dogancanbakir** [comment]
See https://github.com/projectdiscovery/subfinder/issues/1055. Closing this.
