### ISSUE TITLE
interactsh Burp Suite extension failed to register client

### ISSUE THREAD

**Issue by dneel-parikh** [projectdiscovery/interactsh#764]
interactsh Burp Extension jar version 1.0.2

### Current Behavior:
Getting error registering the client in Burp Suite:
"Error registering client"

### Expected Behavior:
Error should not be coming and the generated domain should be working.

### Steps To Reproduce:

1. Install collaborator-1.0.2.jar as an extension to Burp Suite Community Edision v2023.11.3
2. Observed error:
New domain is: cmes7pf24180un32h4sggbqilfmunqusq.oast.pro
Error registering client

**Comment by ehsandeep** [comment]
@dneel-parikh collaborator is community project, here is GitHub project for it - https://github.com/wdahlenburg/interactsh-collaborator
