### ISSUE TITLE
Add subdomains which resolve to cloud metadata addresses

### ISSUE THREAD

**Issue by sullo** [projectdiscovery/interactsh#83]
Add 2 subdomains which resolve to various cloud provider metadata IPs.

For general cloud services, one should resolve to: 169.254.169.254
For Alibaba, one should resolve to: 100.100.100.200

Once created, the metadata-*yaml templates can be updated to use them.

**Comment by ehsandeep** [comment]
@sullo this is now supported with linked PR, confirmed on self-hosted instance, and changes will reflect to interact.sh as soon as we create new release for interactsh and restart the server.

```console
$host aws.hackwithautomation.com
aws.hackwithautomation.com has address 169.254.169.254
aws.hackwithautomation.com mail is handled by 1 mail.hackwithautomation.com.

$host alibaba.hackwithautomation.com
alibaba.hackwithautomation.com has address 100.100.100.200
alibaba.hackwithautomation.com mail is handled by 1 mail.hackwithautomation.com
```
