### ISSUE TITLE
[DEV] Uniform response content type

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/interactsh#88]
- [ ] Using `application/json` instead of `text/plain` on successful response.
- [x] Adding response msg upon successful registration at `/register` endpoint

```http
HTTP/2 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Origin: *
Content-Length: 0
Date: Sat, 11 Sep 2021 09:50:37 GMT

{"message":"registration successful"}
```

**Comment by Mzack9999** [comment]
`application/json` is returned if the request path ends with **.json**
