### ISSUE TITLE
Adding a taint as prefix to payload URL does not work with DNS interactions

### ISSUE THREAD

**Issue by blackthorne** [projectdiscovery/interactsh#898]
### Interactsh version:
v1.2.0

### Current Behavior:
when I add an arbitrary taint as prefix to an interactsh payload it will only work for `http` but not `dns`. 
So if my payload is `cpjdvj4bajfald2br18gurjuymnd6gtyg.oast.site` and I run `dig TAINT_PREFFIX_cpjdvj4bajfald2br18gurjuymnd6gtyg.oast.site` I get no hits on interactsh. 

### Expected Behavior:
Just like for `http` I expect to see a DNS interaction when using a prefix just like I would if I was browsing to `http://TAINT_PREFFIX_cpjdvj4bajfald2br18gurjuymnd6gtyg.oast.site` .

### Steps To Reproduce:
1. run interactsh and generate a `<payload>`
2. run `dig TAINT_PREFFIX_<payload>` (or trigger a DNS request against it in your preferred way)
3. verify that no hits are recorded in interactsh

### Anything else:
The same behaviour is seen on the web app ( https://app.interactsh.com ).

**Comment by blackthorne** [comment]
Any updates on this one? Thank you

**Comment by blackthorne** [comment]
Just a FYI - I'm not sure if this is meant to be applied in app.interactsh.com but in my tests it still did not work.

**Comment by blackthorne** [comment]
app.interactsh.com still not supporting dns correlation ids - any updates?

**Comment by dogancanbakir** [comment]
@blackthorne I've just deployed a version with recent changes. Could you retry it?

**Comment by blackthorne** [comment]
@dogancanbakir it works. thank you!
